### ISSUE TITLE
▶️ Create GitHub Action

### ISSUE THREAD

**Issue by Cynnexis** [Cynnexis/expand-emoji#4]
**Is your feature request related to a problem? Please describe.**
In CI/CD workflows, it would be great to call `expand-emoji` through a GitHub Action to expand emojis in a documentation, for example.

**Describe the solution you'd like**
Create an `action.yml` at the root of the project, and use the Dockerfile to run the action.

Example of usage:

```yaml
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello and goodbye
    steps:
      - name: Create hello file
        run: |
          echo ":wave: Hello world! :earth_africa:" > hello.txt
          echo ":first_quarter_moon_with_face: Goodbye world! :night_with_stars:" > goodbye.txt
      - name: Expand emoji
        uses: Cynnexis/expand-emoji@v1
        with:
          # Pass fiels as JSON array
          files: '["hello.txt", "goodbye.txt"]'
      - name: Print
        run: cat hello.txt goodbye.txt
        # Should print:
        # 👋 Hello world! 🌍
        # 🌛 Goodbye world! 🌃
```

**Describe alternatives you've considered**

**Additional context**
See https://docs.github.com/en/actions/creating-actions
